const midterm_data_66 = [
{
    id: 1,
    img: "./images/product-1.jpg",
    category: 'Ikea',
    title: 'high-back bench',
    desc: '$9.99',
},
{
    id: 2,
    img: "./images/product-2.jpg",
    category: 'Marcos',
    title: 'albany table',
    desc: '$79.99',
},
{
    id: 3,
    img: "./images/product-3.jpg",
    category: 'Caressa',
    title: 'accent chair',
    desc: '$25.99',
},
{
    id: 4,
    img: "./images/product-4.jpg",
    category: 'Ikea',
    title: 'wooden table',
    desc: '$45.99',
},
{
    id: 5,
    img: "./images/product-5.jpg",
    category: 'Marcos',
    title: 'dining table',
    desc: '$6.99',
},
{
    id: 6,
    img: "./images/product-6.jpg",
    category: 'Caressa',
    title: 'sofa set',
    desc: '$69.99',
},
{
    id: 7,
    img: "./images/product-7.jpg",
    category: 'Ikea',
    title: 'modern bookshelf',
    desc: '$8.99',
},
{
    id: 8,
    img: "./images/product-8.jpg",
    category: 'Marcos',
    title: 'emperor bed',
    desc: '$21.99',
},
{
    id: 9,
    img: "./images/product-9.jpg",
    category: 'Caressa',
    title: 'utopia sofa',
    desc: '$39.95',
},
{
    id: 10,
    img: "./images/product-10.jpg",
    title: 'entertainment center',
    category: 'Ikea',
    desc: '$29.98',
},
{
    id: 11,
    img: "./images/product-11.jpg",
    category: 'Marcos',
    title: 'albany sectional',
    desc: '$10.99',
},
{
    id: 12,
    img: "./images/product-12.jpg",
    category: 'Caressa',
    title: 'leather sofa',
    desc: '$9.99',
},
];

export default midterm_data_66;
